# Generated by Django 4.1.5 on 2023-06-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0005_stafffeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stafffeedback',
            name='feedbackreply',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
