# Generated by Django 4.1.5 on 2023-06-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentApp', '0008_studentfeedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentfeedback',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='StudentApp.student'),
        ),
    ]
